config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :products
    root 'products#index'
    #root 'carts#show'
    
    root 'top#main'
    get 'top/main'
    resources :cart_items, only: [:new, :create, :destroy]
    resources :carts, only: [:show]

    
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def current_cart
    if session[:cart_id]
      @cart = Cart.find(session[:cart_id])
    else
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :product
    has_many :cart_items
    has_many :cart_item_products, through: :cart_items, source: :product
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart
    
    def sum_of_price
        product.price * qty
    end
end

app/models/product.rb
class Product < ApplicationRecord
    has_one :carts
    has_one :cart_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    helper_method :current_cart
  
    def current_cart
        if current_user
        # ユーザーとカートの紐付け
        current_cart = current_user.cart || current_user.create_cart!
        else
        # セッションとカートの紐付け
        current_cart = Cart.find_by(id: session[:cart_id]) || Cart.create
        session[:cart_id] ||= current_cart.id
        end
    current_cart
    end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
    
    
    def new
        @cartitem = CartItem.new
    end
    
    def create
        
        if @cart_item.blank?
            @cart_item = current_cart.cart_items.build(product_id: params[:product_id])
        end

        @cart_item.quantity += params[:quantity].to_i
        @cart_item.save
        redirect_to cart_show_path

        #ty = params[:cartitem][:qty]
        #product_id = params[:cartitem][:product_id]
        #cart_id = params[:cartitem][:cart_id]
        #@cartitem = CartItem.new(qty: qty, product_id: product_id, cart_id: cart_id)
        #if @cartitem.save
        #    if my_cart.add_item(product_id: params[:product_id], qty: params[:qty])
        #       flash[:notice] = '商品が追加されました'
        #       redirect_to cart_show_path
        #    else
        #        flash[:notice] = '商品の追加に失敗しました'
        #       render 'new'
        #    end
        #end
    end
    
    def destroy
        cartitem = CartItem.find(params[:id])
        cartitem.destroy
        flash[:notice] = 'カート内の商品が削除されました'
        redirect_to root_path
    end
    
private
    def cart_item_params
        params.require(:cart_item).permit(:item_id, :price, :quantity)
    end
    
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
        @cart = Cart.all
        @product = Product.all
        @cart = Cart.find(params[:id])
        @cart_item = @cart.cart_items.build(product_id: params[:product_id]) if @cart_item.blank?
        @cart_item.save
        @total = @cart_items.inject(0) { |sum, item| sum + item.sum_of_price }
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @product = Product.all
        @cart = Cart.all
    end
    
    def new
        @product = Product.new
    end
    
    def create
        name = params[:product][:name]
        price = params[:product][:price]
        @product = Product.new(name: name, price: price)
        if @product.save
           flash[:notice] = '[１メッセージ追加しました]'
           redirect_to root_path
        else
           render 'new'
        end
    end
    
    def destroy
        product = Product.find(params[:id])
        product.destroy
        redirect_to root_path
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        render 'main'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cart_items/new.html.erb
<%= form_for @cartitem, url: {action: :create} do |f| %>
<p>
    
    <%= f.hidden_field :product_id, value: @product_id %>
    

    <%= @product_id%>

    <%= f.label :qty, '数量' %>
    <%= f.text_field :qty %>
    <%= f.submit '投稿' %>
</p>
<%= link_to '戻る', :back %>
<% end %>

app/views/carts/show.html.erb
<% @cart.each do |cart| %>
    <% if @cart.blank? %>
      <h1>カートに商品はありません</h1>
    <% end %>
    <% @product.each do |product| %>
        <%= product.name %>
        <%= "合計金額：#{@total}円" %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L6_2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<% @product.each do |product| %>
    <p>

        <%= product.name %>
        <%= ' ' %>
        <%= product.price %>
        <%= '円' %>

        <%= link_to '削除', product_path(product), method: :delete %>
        <%= link_to 'カートに追加する', new_cart_item_path(product_id: @product_id) %>
    </p>
<% end %>

<%= link_to '商品を追加する', new_product_path %>
<br>
<%= link_to 'カートの中を見る', new_cart_item_path %>

app/views/products/new.html.erb
<% if @product.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
    <% @product.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul>
<% end %>

<%= form_for @product, url: {action: :create} do |f| %>
<p>
    <%= f.label :name, '名前' %>
    <%= f.text_field :name %>
    <%= f.label :price, '価格' %>
    <%= f.text_field :price %>
    <%= f.submit '投稿' %>
</p>
<%= link_to '戻る', :back %>
<% end %>